name: CI/CD

on:
  push:
    branches:
      - main
      - minty

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/to-doc-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/to-doc-backend:${{ github.sha }}

      - name: 서버 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/app/scripts/be
            chmod +x deploy.sh
            ./deploy.sh ${{ secrets.DOCKERHUB_USERNAME }}/to-doc-backend:${{ github.sha }}
